steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/claimer-devops/ktor-hello-world', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/claimer-devops/ktor-hello-world']
  # Set the correct project
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['config', 'set', 'project', 'claimer-dev-two']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'ktor-hello-world', '--image', 'gcr.io/claimer-devops/ktor-hello-world:latest', '--region', 'europe-west2', '--project', 'claimer-dev-two']
  # Run pulumi up
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: /bin/sh
    args:
      - '-c'
      - 'chmod +x *.sh && ./pulumi.sh'
    env:
      # We use substitution for an example. Your Pulumi access token is sensitive and as such should be encrypted.
      # See the Encrypted Variables section below on how to do that.
      - 'PULUMI_ACCESS_TOKEN=$_INSECURE_SUBSTITUTION_PULUMI_ACCESS_TOKEN'
      - 'BUILD_TYPE=$_BUILD_TYPE'
images:
  - gcr.io/claimer-devops/ktor-hello-world
options:
  pool:
    name: 'projects/785020424916/locations/europe-west2/workerPools/pool-1'